# Note we use the fly secret api to set
# DB_PASSWORD and DB_HOST
app = "tenant-xwiki"
primary_region = "iad"

[build]
    dockerfile = "xwiki:stable-postgres-tomcat"

[env]
    DB_USER = "xwiki"

[http_service]
    internal_port = 8080
    force_https = true
    auto_stop_machines = "stop"
    auto_start_machines = true
    min_machines_running = 0
    [http_service.concurrency]
        type = "requests"
        soft_limit = 200
        hard_limit = 250

[mounts]
    source = "xwiki-data"
    destination = "/usr/local/xwiki/data"
    initial_size = "2gb"
