# fly.toml app configuration file generated for rva-tenant-postgres on 2025-03-16T15:46:38-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rva-tenant-postgres'
primary_region = 'iad'

[build]
  image = 'docker.io/postgres:17.4'

[env]
  POSTGRES_USER = 'xwiki'
  PG_DATA = '/data/pg_data'

[[mounts]]
  source = 'xwiki_postgres_data'
  destination = '/data'
  initial_size = '4gb'

[[services]]
  protocol = 'tcp'
  internal_port = 5432

  [[services.ports]]
    port = 5432
    handlers = ['pg_tls']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
