# Note we use the fly secret api to set
# DB_PASSWORD and DB_HOST
app = "rva-tenant-xwiki"
primary_region = "iad"

[build]
    image = "docker.io/xwiki:stable-postgres-tomcat"

[env]
    DB_USER = "xwiki"
    DB_HOST = "rva-tenant-postgres.internal"

[http_service]
    internal_port = 8080
    force_https = true
    auto_stop_machines = "stop"
    auto_start_machines = true
    min_machines_running = 0
    [http_service.concurrency]
        type = "requests"
        soft_limit = 200
        hard_limit = 250

[[vm]]
    size = "shared-cpu-2x"
    memory = "4gb"

[mounts]
    source = "xwiki_app_data"
    destination = "/usr/local/xwiki/data"
    initial_size = "20gb"
